In [2]:
#Importing Libraries
import pandas as pd
import numpy as np

In [6]:
#loading the dataset
df = pd.read_csv('../AI-ML Group Project/Dataset/stroke_prediction_dataset.csv')
#".." means to go up one directory

In [8]:
#View the top 5 rows of the dataset
display(df.head())

,Patient ID,Patient Name,Age,Gender,Hypertension,Heart Disease,Marital Status,Work Type,Residence Type,Average Glucose Level,...,Alcohol Intake,Physical Activity,Stroke History,Family History of Stroke,Dietary Habits,Stress Levels,Blood Pressure Levels,Cholesterol Levels,Symptoms,Diagnosis
0,18153,Mamooty Khurana,56,Male,0,1,Married,Self-employed,Rural,130.91,...,Social Drinker,Moderate,0,Yes,Vegan,3.48,140/108,"HDL: 68, LDL: 133","Difficulty Speaking, Headache",Stroke
1,62749,Kaira Subramaniam,80,Male,0,0,Single,Self-employed,Urban,183.73,...,Never,Low,0,No,Paleo,1.73,146/91,"HDL: 63, LDL: 70","Loss of Balance, Headache, Dizziness, Confusion",Stroke
2,32145,Dhanush Balan,26,Male,1,1,Married,Never Worked,Rural,189.00,...,Rarely,High,0,Yes,Paleo,7.31,154/97,"HDL: 59, LDL: 95","Seizures, Dizziness",Stroke
3,6154,Ivana Baral,73,Male,0,0,Married,Never Worked,Urban,185.29,...,Frequent Drinker,Moderate,0,No,Paleo,5.35,174/81,"HDL: 70, LDL: 137","Seizures, Blurred Vision, Severe Fatigue, Head...",No Stroke
4,48973,Darshit Jayaraman,51,Male,1,1,Divorced,Self-employed,Urban,177.34,...,Rarely,Low,0,Yes,Pescatarian,6.84,121/95,"HDL: 65, LDL: 68",Difficulty Speaking,Stroke

In [12]:
#Checking the dataframe's dimensions, data types & non missing value counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Patient ID                15000 non-null  int64
 1   Patient Name              15000 non-null  object
 2   Age                       15000 non-null  int64
 3   Gender                    15000 non-null  object
 4   Hypertension              15000 non-null  int64
 5   Heart Disease             15000 non-null  int64
 6   Marital Status            15000 non-null  object
 7   Work Type                 15000 non-null  object
 8   Residence Type            15000 non-null  object
 9   Average Glucose Level     15000 non-null  float64
 10  Body Mass Index (BMI)     15000 non-null  float64
 11  Smoking Status            15000 non-null  object
 12  Alcohol Intake            15000 non-null  object
 13  Physical Activity         15000 non-null  object
 14  Stroke History            15000 non-null  int64
 15  Family History of Stroke  15000 non-null  object
 16  Dietary Habits            15000 non-null  object
 17  Stress Levels             15000 non-null  float64
 18  Blood Pressure Levels     15000 non-null  object
 19  Cholesterol Levels        15000 non-null  object
 20  Symptoms                  12500 non-null  object
 21  Diagnosis                 15000 non-null  object
dtypes: float64(3), int64(5), object(14)
memory usage: 2.5+ MB

In [14]:
#Only showing the columns with missing values
missing_values = df.isnull().sum()
missing_values = missing_values[missing_values > 0] #Filter columns with missing values > 0
print(missing_values)

Symptoms    2500
dtype: int64

In [17]:
#Handling missing values for "Symptoms" column
if df["Symptoms"].isnull().sum() > 0:
    #Adding a binary indicator as a missing indicator
    df["Symptoms_missing"] = df["Symptoms"].isnull().astype(int)

    #Filling in missing values as "Uknown"
    df.fillna({"Symptoms":"Unknown"}, inplace = True)

In [19]:
#Dataframe after handling missing values:
df.isnull().sum()

Patient ID                  0
Patient Name                0
Age                         0
Gender                      0
Hypertension                0
Heart Disease               0
Marital Status              0
Work Type                   0
Residence Type              0
Average Glucose Level       0
Body Mass Index (BMI)       0
Smoking Status              0
Alcohol Intake              0
Physical Activity           0
Stroke History              0
Family History of Stroke    0
Dietary Habits              0
Stress Levels               0
Blood Pressure Levels       0
Cholesterol Levels          0
Symptoms                    0
Diagnosis                   0
Symptoms_missing            0
dtype: int64

In [20]:
#Visualizing top 12 rows after change
df.head(12)

,Patient ID,Patient Name,Age,Gender,Hypertension,Heart Disease,Marital Status,Work Type,Residence Type,Average Glucose Level,...,Physical Activity,Stroke History,Family History of Stroke,Dietary Habits,Stress Levels,Blood Pressure Levels,Cholesterol Levels,Symptoms,Diagnosis,Symptoms_missing
0,18153,Mamooty Khurana,56,Male,0,1,Married,Self-employed,Rural,130.91,...,Moderate,0,Yes,Vegan,3.48,140/108,"HDL: 68, LDL: 133","Difficulty Speaking, Headache",Stroke,0
1,62749,Kaira Subramaniam,80,Male,0,0,Single,Self-employed,Urban,183.73,...,Low,0,No,Paleo,1.73,146/91,"HDL: 63, LDL: 70","Loss of Balance, Headache, Dizziness, Confusion",Stroke,0
2,32145,Dhanush Balan,26,Male,1,1,Married,Never Worked,Rural,189.00,...,High,0,Yes,Paleo,7.31,154/97,"HDL: 59, LDL: 95","Seizures, Dizziness",Stroke,0
3,6154,Ivana Baral,73,Male,0,0,Married,Never Worked,Urban,185.29,...,Moderate,0,No,Paleo,5.35,174/81,"HDL: 70, LDL: 137","Seizures, Blurred Vision, Severe Fatigue, Head...",No Stroke,0
4,48973,Darshit Jayaraman,51,Male,1,1,Divorced,Self-employed,Urban,177.34,...,Low,0,Yes,Pescatarian,6.84,121/95,"HDL: 65, LDL: 68",Difficulty Speaking,Stroke,0
5,29307,Advika Kota,62,Female,0,0,Single,Private,Urban,91.60,...,High,0,No,Gluten-Free,4.85,132/64,"HDL: 80, LDL: 69",Severe Fatigue,Stroke,0
6,25525,Elakshi Karan,40,Female,1,0,Married,Private,Urban,77.83,...,Low,1,No,Vegetarian,6.38,178/105,"HDL: 31, LDL: 134",Unknown,No Stroke,1
7,4809,Shalv Dugar,61,Female,0,1,Divorced,Government Job,Rural,194.73,...,Moderate,1,No,Vegan,5.85,179/72,"HDL: 66, LDL: 134",Loss of Balance,Stroke,0
8,7372,Raghav Handa,72,Female,1,1,Married,Self-employed,Rural,72.99,...,High,1,No,Vegetarian,0.73,141/106,"HDL: 71, LDL: 140","Loss of Balance, Dizziness, Difficulty Speaking",Stroke,0
9,37504,Krish Kulkarni,82,Male,0,0,Divorced,Self-employed,Urban,111.23,...,High,1,Yes,Non-Vegetarian,8.39,119/88,"HDL: 32, LDL: 88",Unknown,No Stroke,1
10,15298,Neelofar Devan,41,Male,0,1,Divorced,Government Job,Urban,94.90,...,Low,1,Yes,Pescatarian,1.56,91/80,"HDL: 32, LDL: 114","Difficulty Speaking, Numbness, Weakness, Sever...",No Stroke,0
11,36017,Anaya Koshy,72,Female,0,0,Divorced,Private,Urban,155.32,...,Moderate,0,Yes,Paleo,8.71,127/110,"HDL: 55, LDL: 96","Loss of Balance, Blurred Vision",Stroke,0

In [21]:
#As showm above only the "Symptoms" column had missing values, 2500 rows to be precise

#A binary indicator column "Symptoms_missing" was added as in many cases, missingness itself can carry predictive power
#for instance, patients who are too sick to report symptoms might have worse outcomes.

#Affected rows were filled with "Unknown" as someone may not have reported symptoms due to death, incapacity, or incomplete records.